"""Deep recursive Vimshottari dasha periods (MD/AD/PD/Sookshma/Prana/...).

The arc-to-time mapping is:

1. The Moon's position inside its nakshatra fixes the birth Mahadasha lord and
   how much of that Mahadasha had already elapsed at birth.
2. Every deeper lord is found by recursively dividing the parent's arc in
   proportion to the Vimshottari year counts.
3. Arc is mapped linearly onto time using the parent's own duration.

Two distinct queries are supported and must not be conflated:

* :func:`dasha_segments` / :func:`birth_stack` - the stack implied by the
  **birth** Moon longitude.  Immutable for a given chart.
* :func:`deep_current_periods` - the stack active at an arbitrary
  **query datetime**.  This walks the real timeline forward from the absolute
  mahadasha start and is what KP Stellar's dasha panel displays.

The previous implementation returned the birth stack regardless of the datetime
it was handed, so the "current" panel never advanced past the first period of
each level.

Exact-mas recursion (level 4+)
------------------------------
Level-4-and-deeper arc segments used to be produced by accumulating float
``cursor += span_deg`` inside :func:`_child_segment`; the drift made the nine
children fail to tile their parent exactly, which (a) flipped boundary cases
and (b) raised ``ValueError`` for most longitudes whose early children carry
long spans.  The recursion now lives entirely in the integer/Fraction
milliarcsecond space of :mod:`kpastro.arithmetic`
(:func:`~kpastro.arithmetic.child_tiling_mas`): each child edge is one exact
multiply of the parent endpoints — ``start + span * cum_years / 120`` — so
adjacency holds at every depth and no absolute-longitude accumulation exists
to drift.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta

from .constants import (
    VIMSHOTTARI_INDEX,
    VIMSHOTTARI_ORDER,
    VIMSHOTTARI_TOTAL_YEARS,
    VIMSHOTTARI_YEARS,
)
from .arithmetic import (
    BOUNDARY_TOL_MAS,
    MAS_PER_DEG,
    child_tiling_mas,
    deg_to_mas,
    locate_in_tiling,
    mas_to_deg,
)
from .dasha import (
    DASHA_LEVEL_NAMES,
    DAYS_PER_YEAR,
    absolute_periods,
    dasha_balance,
    mahadasha_days,
)
from .vedic import (
    STAR_SPAN_ARCMIN,
    STAR_SPAN_DEG,
    _probe_mas,
    normalize_longitude,
    star_index,
    star_lord,
    sub_info,
    sub_sub_info,
)

__all__ = [
    "DASHA_LEVEL_NAMES",
    "DeepDashaPeriod",
    "birth_stack",
    "dasha_segments",
    "deep_current_periods",
    "deep_lords_at",
]


@dataclass(frozen=True)
class DeepDashaPeriod:
    """One current Vimshottari level: lord, start/end UT, duration, balance."""

    level: int
    name: str
    lord: str
    start: datetime
    end: datetime
    duration_days: float
    balance_days: float


@dataclass(frozen=True)
class _DashaSegment:
    """Arc segment for one dasha level."""

    level: int
    lord: str
    start_deg: float
    end_deg: float
    span_arcmin: float


def _level_name(level: int) -> str:
    if 1 <= level <= len(DASHA_LEVEL_NAMES):
        return DASHA_LEVEL_NAMES[level - 1]
    return f"Level {level}"


# ---------------------------------------------------------------------------
# Birth-anchored arc segments
# ---------------------------------------------------------------------------

def _child_segment(lon: float, parent: _DashaSegment) -> _DashaSegment:
    """Find the child segment containing ``lon`` inside ``parent``.

    Exact-mas recursion (fixes the legacy drift class): the nine children are
    generated by :func:`kpastro.arithmetic.child_tiling_mas` as exact
    ``start + span * cum_years / 120`` rationals of the parent arc — never by
    accumulating ``cursor += span_deg`` floats.  The legacy version lost
    adjacency at roughly every third boundary and raised ``ValueError`` for
    ~98% of longitudes inside a sub whose early children are Rahu/Saturn/
    Mercury (the accumulated cursor overshot the last computed end); both
    failure modes are structurally impossible now.

    Boundary policy is the unified one: forward-push by
    :data:`~kpastro.arithmetic.BOUNDARY_TOL_MAS` (≡ legacy ``+1e-9°``),
    clamped to just below the parent end (≡ legacy ``end - 1e-12°``).
    """
    lon = normalize_longitude(lon)
    m = _probe_mas(lon)
    parent_start_m = deg_to_mas(parent.start_deg)
    parent_end_m = deg_to_mas(parent.end_deg)
    probe = min(m + BOUNDARY_TOL_MAS, parent_end_m - BOUNDARY_TOL_MAS)
    tiling = child_tiling_mas(parent_start_m, parent_end_m, parent.lord)
    lord, _k, start_m, end_m = locate_in_tiling(tiling, probe)
    return _DashaSegment(
        level=parent.level + 1,
        lord=lord,
        start_deg=mas_to_deg(start_m),
        end_deg=mas_to_deg(end_m),
        span_arcmin=float((end_m - start_m) * 60 / MAS_PER_DEG),
    )


def dasha_segments(moon_lon: float, depth: int = 5) -> list[_DashaSegment]:
    """Return arc segments for dasha levels 1..depth.

    Level 1: Mahadasha / nakshatra segment
    Level 2: Antardasha / sub segment
    Level 3: Pratyantardasha / sub-sub segment
    Level 4+: recursively divided segments
    """
    if depth < 1:
        raise ValueError("depth must be >= 1")

    lon = normalize_longitude(moon_lon)

    # Level 1: Mahadasha / nakshatra
    idx = star_index(lon)
    star_start = idx * STAR_SPAN_DEG
    star_end = (idx + 1) * STAR_SPAN_DEG
    md_lord = star_lord(lon)

    segments: list[_DashaSegment] = [
        _DashaSegment(
            level=1,
            lord=md_lord,
            start_deg=star_start,
            end_deg=star_end,
            span_arcmin=STAR_SPAN_ARCMIN,
        )
    ]

    if depth == 1:
        return segments

    # Level 2: Antardasha / sub
    sub = sub_info(lon)
    segments.append(
        _DashaSegment(
            level=2,
            lord=sub.lord,
            start_deg=sub.start_deg,
            end_deg=sub.end_deg,
            span_arcmin=sub.span_arcmin,
        )
    )

    if depth == 2:
        return segments

    # Level 3: Pratyantardasha / sub-sub
    subsub = sub_sub_info(lon)
    segments.append(
        _DashaSegment(
            level=3,
            lord=subsub.lord,
            start_deg=subsub.start_deg,
            end_deg=subsub.end_deg,
            span_arcmin=subsub.span_arcmin,
        )
    )

    if depth == 3:
        return segments

    # Level 4 and deeper
    parent = segments[-1]
    for _ in range(4, depth + 1):
        child = _child_segment(lon, parent)
        segments.append(child)
        parent = child

    return segments


def birth_stack(moon_lon: float, depth: int = 5) -> list[str]:
    """Lords of the dasha stack implied by the birth Moon, MD first."""
    return [seg.lord for seg in dasha_segments(moon_lon, depth=depth)]


# ---------------------------------------------------------------------------
# Query-date resolution
# ---------------------------------------------------------------------------

def deep_current_periods(
    moon_lon: float,
    birth_utc: datetime,
    depth: int = 5,
    query_utc: datetime | None = None,
) -> list[DeepDashaPeriod]:
    """Compute the Vimshottari stack active at ``query_utc``, levels 1..depth.

    ``moon_lon`` is the **sidereal birth** Moon longitude; ``birth_utc`` is the
    birth moment in UTC (it anchors the mahadasha).  ``query_utc`` defaults to
    ``birth_utc``, which reproduces the birth stack.

    All datetimes in the result are UTC.
    """
    if depth < 1:
        raise ValueError("depth must be >= 1")

    instant = query_utc or birth_utc
    raw = absolute_periods(moon_lon, birth_utc, instant, depth=depth)

    elapsed_days = (instant - birth_utc).total_seconds() / 86400.0

    periods: list[DeepDashaPeriod] = []
    for p in raw:
        start = birth_utc + timedelta(days=p.start_days)
        end = birth_utc + timedelta(days=p.end_days)
        periods.append(
            DeepDashaPeriod(
                level=p.level,
                name=_level_name(p.level),
                lord=p.lord,
                start=start,
                end=end,
                duration_days=p.duration_days,
                balance_days=p.end_days - elapsed_days,
            )
        )
    return periods


def deep_lords_at(
    moon_lon: float,
    birth_utc: datetime,
    depth: int = 5,
    query_utc: datetime | None = None,
) -> list[str]:
    """Convenience: just the lord names of the active stack, MD first."""
    return [
        p.lord
        for p in deep_current_periods(moon_lon, birth_utc, depth, query_utc)
    ]


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------

def birth_balance_summary(moon_lon: float) -> dict[str, float]:
    """Elapsed / remaining mahadasha days at birth (debug + rectification aid)."""
    bal = dasha_balance(moon_lon)
    total = mahadasha_days(bal.mahadasha_lord)
    return {
        "mahadasha_lord_years": VIMSHOTTARI_YEARS[bal.mahadasha_lord],
        "mahadasha_total_days": total,
        "elapsed_days": total - bal.mahadasha_days,
        "balance_days": bal.mahadasha_days,
        "balance_years": bal.mahadasha_days / DAYS_PER_YEAR,
    }
